/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    DescribedTable: typeof import('./src/components/DescribedTable.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ScatterPlot: typeof import('./src/components/ScatterPlot.vue')['default']
  }
}
